# Site settings
title: Rabid Tunes
description: Rabid Tunes resume webpage
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rabidtunes.github.io"

# User settings
username: Rabid Tunes
user_description: Welcome to my personal page! I'm Rabid Tunes, a video game music composer. You can see my work by clicking the icons above!
user_title: Video game music composer
email: rabidtunesmusic@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
